# Generated by Django 5.1.3 on 2025-10-06 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employerprofil",
            name="profil_image",
        ),
        migrations.AddField(
            model_name="employerprofil",
            name="address",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employerprofil",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="profil_employer"),
        ),
        migrations.AddField(
            model_name="employerprofil",
            name="phone_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employerprofil",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employerprofil",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="offer",
            name="employer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offers",
                to="job.employerprofil",
            ),
        ),
    ]
